Mapper and repository
ita-social-projects/StreetCode pull request #11
Opened 2022-12-13 19:32 UTC by Tatiana2424

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-12-13 19:59 UTC, dimasster approved these changes

2022-12-13 22:30 UTC, LanchevychMaxym requested changes

2022-12-13 22:30 UTC, LanchevychMaxym commented on Streetcode/Streetcode.BLL/Services/Streetcode/TextContent/FactService.cs
> +        // return _repositoryWrapper.FactRepository.GetFactsByStreetcode();
Let's add TODO here to clean this after merge

2022-12-13 22:30 UTC, LanchevychMaxym commented on Streetcode/Streetcode.DAL/Repositories/Interfaces/Media/IAudioRepository.cs
> +    public void DeleteAudioAsync();
I think we can remove these duplicated methods from all repository's interfaces and just inherit them from IRepositoryBase<T>

2022-12-13 22:30 UTC, LanchevychMaxym commented on Streetcode/Streetcode.DAL/Repositories/Realizations/AdditionalContent/SubtitleRepository.cs
> +        return "GetSubtitlesByStreetcode";
Let's add TODO for all code that we will have to clean

2022-12-13 22:30 UTC, LanchevychMaxym commented on Streetcode/Streetcode/Controllers/FactController.cs
> +        return _factService.GetFactsByStreetcode();
Let's use Async

2022-12-13 22:30 UTC, LanchevychMaxym commented on Streetcode/Streetcode/Extensions/ServiceCollectionExtentions.cs
> +using EPlast.BLL.Services.Logging;
Very strange namespace

2022-12-14 08:33 UTC, AleXLaeR requested changes
Please thouroughly review my comments & impovement suggestions.

2022-12-14 08:33 UTC, AleXLaeR commented on Streetcode/Streetcode.BLL/Interfaces/Logging/ILoggerService.cs
> +namespace EPlast.BLL.Interfaces.Logging
Copy & Paste code;
Check namespaces everywhere you did that.

2022-12-14 08:33 UTC, AleXLaeR commented on Streetcode/Streetcode.BLL/Interfaces/Streetcode/TextContent/ITextService.cs
> +public interface ITextService
We don't need some of the repository interfaces;
You can just make its realization dependent on IRepositoryBase.

2022-12-14 08:33 UTC, AleXLaeR commented on Streetcode/Streetcode.BLL/Interfaces/Streetcode/TextContent/ITermService.cs
> +public interface ITermService
We don't need some of the repository interfaces;
You can just make its realization dependent on IRepositoryBase.

2022-12-14 08:33 UTC, AleXLaeR commented on Streetcode/Streetcode.BLL/Mapping/AdditionalContent/Coordinates/CoordinateProfile.cs
> +using AutoMapper;
Fix indentation problems in all files from this commit (Unnecessary blank lines, unconventional inheritance spacing, etc).

2022-12-14 08:33 UTC, AleXLaeR commented on Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IRepositoryBase.cs
> +     IQueryable<T> GetAll();
When working with IQueryable interface, we are posing a "question", applying all necessary filters right off the bat.
Hence the method's name should be "FindAll" and not "GetAll".

2022-12-14 08:33 UTC, AleXLaeR commented on Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IRepositoryBase.cs
> +     Task<IEnumerable<T>> GetAllAsync();
Also, it wouldn't hurt to add optional Expressions/Predicates, bound to default/null by default.

2022-12-14 08:33 UTC, AleXLaeR commented on Streetcode/Streetcode.DAL/Repositories/Interfaces/Base/IRepositoryBase.cs
> +public interface IRepositoryBase<T>
As a side note, during the latter stages of our development plan we would surely face the need insome form of conditional fetching of only one entity from the repo.
Hence, the base repo interface must be supplied with FirstOrDefaultAsync/SingleOrDefaultAsync methods.

2022-12-14 08:33 UTC, AleXLaeR commented on Streetcode/Streetcode/Extensions/ServiceCollectionExtentions.cs
>          services.AddScoped<IPartnersService, PartnersService>();
Please divide intergration of built-in services and custom ones into their own extension methods.

2022-12-14 17:58 UTC, AleXLaeR approved these changes
All done great.

2022-12-14 19:54 UTC, LanchevychMaxym approved these changes
LGTM!

2022-12-14 19:56 UTC, merged