Last 10 streetcode cards displaying on main page
ita-social-projects/StreetCode pull request #1141
Opened 2024-02-01 09:33 UTC by FlSlaves

## Summary of change

[Issue](https://github.com/orgs/ita-social-projects/projects/21/views/1?filterQuery=fls&pane=issue&itemId=48642644)

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-02-05 08:32 UTC, Oleh-Kril commented on Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllMainPage/GetAllStreetcodesMainPageHandler.cs
The name of handler does not display the new logic

2024-02-05 08:32 UTC, Oleh-Kril requested changes
Fix comments

2024-02-05 08:32 UTC, Oleh-Kril commented on Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetPageMainPage/GetPageOfStreetcodesMainPageHandler.cs
> +                OrderByDescending(sc => sc.UpdatedAt).Take(10);
I want to pass the number from frontend, don't use 10 everywhere please

2024-02-12 20:04 UTC, malyna2 approved these changes
Сonsider Oleg's comments, then it would be ok

2024-02-27 20:15 UTC, NadiaKishchuk commented on Streetcode/Streetcode.BLL/MediatR/Streetcode/Streetcode/GetAllMainPage/GetAllStreetcodesMainPageHandler.cs
> +                return Result.Ok(_mapper.Map<IEnumerable<StreetcodeMainPageDTO>>(streetcodes).OrderByDescending(c => c.UpdatedAt).Take(10));
I believe this is better to create the constant variable for that 10

2024-04-12 11:51 UTC, closed without merging