Feature/issue 1205
ita-social-projects/StreetCode pull request #1387
Opened 2024-04-19 13:17 UTC by vasylashka

Found out that valid range for LogoType property is [0, 7], updated enum with current values that are used in the frontend for displaying logos and wrote a field validation.

2024-04-22 11:41 UTC, Lazy-Lenny requested changes

2024-04-22 11:41 UTC, Lazy-Lenny commented on Streetcode/Streetcode.DAL/Enums/LogoType.cs
Add new line at the end of file

2024-04-23 17:29 UTC, vasylashka commented on Streetcode/Streetcode.DAL/Enums/LogoType.cs
Done!

2024-04-23 19:33 UTC, Lazy-Lenny approved these changes

2024-04-24 18:30 UTC, yaakymiv approved these changes

2024-04-26 05:32 UTC, merged