Made tests for sources handlers and withInderexisthandler
ita-social-projects/StreetCode pull request #155
Opened 2023-03-29 14:35 UTC by DanyilTerentiev

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @Kasterov  @ormykhalyshyn @VitaliiKulinskyi 

### Second Level Review
#
- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-03-29 18:25 UTC, Tysyatsky approved these changes
Unit test at their finest. Great work :)

2023-03-29 18:42 UTC, Katerix requested changes
Good job for starters! Please read review comments and  change similar code in all necessary files)

2023-03-29 18:42 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/SourcesTests/GetCategoriesByStreetcodeIdTest.cs
> +
please remove unnecessary usings

2023-03-29 18:42 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/SourcesTests/GetCategoriesByStreetcodeIdTest.cs
> +
try not to leave extra empty lines

2023-03-29 18:42 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/SourcesTests/GetCategoriesByStreetcodeIdTest.cs
> +            var result = await handler.Handle(new GetCategoriesByStreetcodeIdQuery(1), CancellationToken.None);
it is a better practice to keep values in (test) variables - avoid using "magical" numbers

2023-03-29 18:42 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/SourcesTests/GetCategoryByIdTest.cs
> +        );
maybe some extra 'tab' spacings on 46, 47 line will make code prittier

2023-03-29 18:42 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/SourcesTests/GetSubCategoriesByCategoryIdTest.cs
> +
same here

2023-03-29 18:42 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/SourcesTests/GetSubCategoriesByCategoryIdTest.cs
> +
same here

2023-03-29 18:42 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/SourcesTests/GetSubCategoriesByCategoryIdTest.cs
> +        {
you can remove this defauilt declaration (you already have inline data instead)

2023-03-29 18:42 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/WithIndexExistHandlerTest.cs
> +using Xunit.Sdk;
same here

2023-03-30 09:37 UTC, Katerix approved these changes
Awesome!

2023-03-30 09:41 UTC, merged