Implement tests to Term and HistoricalContext
ita-social-projects/StreetCode pull request #156
Opened 2023-03-29 18:17 UTC by Dobriyr

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] someone from second team

### Second Level Review

- [ ] anotherone from second team

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-03-29 18:28 UTC, Tysyatsky requested changes
Tests are pretty fine, just comment on code style.

2023-03-29 18:28 UTC, Tysyatsky commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Terms/DeleteTermHendlerTests.cs
> +		public async Task ShouldDeleteSuccessfully(int id) {
move brackets to the next line in all files. It is important

2023-03-29 18:54 UTC, Katerix requested changes
in general well done. My only advice is be attentive to code styling and be aware of inlineData attribute

2023-03-29 18:54 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Terms/CreateTermHandlerTests.cs
> +
please avoid using magical numbers, it is a good practice to move them to attribute [InlineData()]

2023-03-29 18:54 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Terms/CreateTermHandlerTests.cs
> +			return new();
you can either reduce code complexity by using this: 
private static Term GetTerm() => new(); 
or move curly brace to the next line.

2023-03-29 18:54 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Terms/UpdateTermHendlerTests.cs
> +			//Arrange
here you have one code styling (method's curly braces)

2023-03-29 18:54 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Timeline/HistoricalContextTests/GetAllHistoricalContextTest.cs
> +			//Arrange
and here you have another (maybe it is better to follow one style)

2023-03-29 18:54 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Timeline/HistoricalContextTests/GetAllHistoricalContextTest.cs
> +			}
same here (please be attentive to styling code, this will make it more readable)

2023-03-29 18:54 UTC, Katerix commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Timeline/HistoricalContextTests/GetAllHistoricalContextTest.cs
> +			var historicalContexts = new List<HistoricalContext>() {
same here

2023-04-10 07:54 UTC, Tysyatsky approved these changes

2023-04-25 13:55 UTC, merged