changed update-iteration.yml to move tasks to the next iteration
ita-social-projects/StreetCode pull request #1669
Opened 2024-08-20 15:43 UTC by darkravchuk

dev
## JIRA

* [ticket-1662](https://github.com/ita-social-projects/StreetCode/issues/1662)

## Code reviewers

- [ ] @Mikhail-Kolpakov

- [ ] @mythter

- [ ] @sashapanasiuk5

## Summary of issue

Modified the workflow to move all tasks to the next iteration except those with statuses  "Ready to release", and "Done".

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2024-08-20 15:54 UTC, mythter approved these changes

2024-08-21 11:07 UTC, Mikhail-Kolpakov approved these changes

2024-08-21 11:10 UTC, sashapanasiuk5 approved these changes

2024-08-21 11:49 UTC, sashapanasiuk5 requested changes
I think "Blocked" status should also be moved to the next iteration

2024-08-21 12:22 UTC, sashapanasiuk5 approved these changes

2024-09-22 21:11 UTC, merged