Migration
ita-social-projects/StreetCode pull request #178
Opened 2023-04-12 16:19 UTC by NadiaKishchuk

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-04-13 11:22 UTC, Kasterov approved these changes
Well done!

2023-04-13 11:24 UTC, Kasterov approved these changes

2023-04-13 11:24 UTC, Kasterov commented on Streetcode/Streetcode.BLL/Util/DateToStringConverter.cs
> +        }
Dear Nadya,

I am writing to say, maybe it is better to use here switch pattern?

Example:
return dateTime.Month switch
{
12 or 1 or 2 => "зима",
3 or 4 or 5 => "весна",
6 or 7 or 8 => "літо",
_ => "осінь",
};

Waiting for your reply,
Viacheslav

2023-04-13 12:21 UTC, Tysyatsky requested changes

2023-04-13 12:49 UTC, NadiaKishchuk commented on Streetcode/Streetcode.BLL/MediatR/Partners/Create/CreatePartnerHandler.cs
> +>>>>>>> origin
oh
i think that i push the resolving of it
thanks)

2023-04-20 18:28 UTC, Tysyatsky approved these changes

2023-04-25 13:53 UTC, closed without merging