Additional text new text field size with migration valerii
ita-social-projects/StreetCode pull request #209
Opened 2023-05-15 09:16 UTC by ValDekh

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-05-15 09:41 UTC, ormykhalyshyn requested changes
Only one migration, not 6, also change the connection string when making a pull request.

2023-05-15 09:41 UTC, ormykhalyshyn commented on Streetcode/Streetcode.DAL/Persistence/Migrations/20230511081334_NewSizeOfTextFields.Designer.cs
you need to do only one migration not 4 or 5

2023-05-15 22:46 UTC, ValDekh commented on Streetcode/Streetcode.DAL/Persistence/Migrations/20230511081334_NewSizeOfTextFields.Designer.cs
done

2023-05-17 06:33 UTC, ormykhalyshyn requested changes

2023-05-17 06:33 UTC, ormykhalyshyn commented on Streetcode/Streetcode.DAL/Persistence/Migrations/StreetcodeDbContextModelSnapshot.cs
You must rename this migration. Firstly, you must remove this migration and name it Initial.

2023-05-17 08:24 UTC, ValDekh commented on Streetcode/Streetcode.DAL/Persistence/Migrations/StreetcodeDbContextModelSnapshot.cs
Done

2023-05-17 09:45 UTC, Dobriyr requested changes
Looks nice but need to add some changes

2023-05-18 20:34 UTC, ValDekh commented on Streetcode/StreetCode.Client
Done

2023-05-18 20:34 UTC, ValDekh commented on Streetcode/Streetcode.WebApi/Controllers/Streetcode/StreetcodeController.cs
> +            return BadRequest();
Done

2023-05-18 20:34 UTC, ValDekh commented on Streetcode/Streetcode.WebApi/appsettings.Local.json
Done

2023-05-18 20:35 UTC, ValDekh commented on Streetcode/Streetcode.WebApi/appsettings.json
Done

2023-05-22 13:23 UTC, closed without merging