Add appsettings & environment variables
ita-social-projects/StreetCode pull request #22
Opened 2022-12-21 19:03 UTC by grygorenkod

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2022-12-21 19:47 UTC, LanchevychMaxym requested changes

2022-12-21 19:47 UTC, LanchevychMaxym commented on Streetcode/Streetcode/Program.cs
> +//}
You can remove these comments, these should be in Nuke SetupEnvironmentVariables target

2022-12-21 19:47 UTC, LanchevychMaxym commented on Streetcode/Streetcode/appsettings.Development.json
> -    }
Let's move these logging overriding to appsettings.json

2022-12-21 19:47 UTC, LanchevychMaxym commented on Streetcode/Streetcode/appsettings.IntegrationTests.json
> +    "DefaultConnection": "Server=(localdb)\\MSSQLLocalDB;Database=_CHANGE_ME;Trusted_Connection=True;MultipleActiveResultSets=true"
Let's rename this "DefaultConnection" to "Main" and in future you will have to add here connection string to your database in docker container

2022-12-21 19:47 UTC, LanchevychMaxym commented on Streetcode/Streetcode/appsettings.Production.json
> +  }
You can remove Backend url

2022-12-21 19:47 UTC, LanchevychMaxym commented on Streetcode/Streetcode/Program.cs
>  if (app.Environment.IsDevelopment())
Let's use that only in Local env

2022-12-21 19:47 UTC, LanchevychMaxym commented on Streetcode/Streetcode/Program.cs
> +    app.UseExceptionHandler("/Home/Error");
Do we have this error handling page?

2022-12-21 19:47 UTC, LanchevychMaxym commented on Streetcode/Streetcode/Program.cs
> +if (!app.Environment.IsDevelopment())
I guess here should be Local instead of Development

2022-12-22 18:11 UTC, dimasster commented on Streetcode/Streetcode/Program.cs
> +    config.AddEnvironmentVariables("STREETCODE_");
why we need _ in the end of variable, maybe it is malformed name

2022-12-23 19:18 UTC, LanchevychMaxym approved these changes

2022-12-23 19:18 UTC, LanchevychMaxym commented on Streetcode/Streetcode/Properties/launchSettings.json
> +        "ASPNETCORE_ENVIRONMENT": "Production"
This should be local

2022-12-23 19:18 UTC, LanchevychMaxym commented on Streetcode/Streetcode/appsettings.Local.json
> +    "DefaultConnection": "Server=localhost;Database=StreetcodeDb;UserId=sa;Password=Admin@1234;MultipleActiveResultSets=true"
In all configs this section should have the same name "Main"

2022-12-23 22:21 UTC, Tatiana2424 approved these changes

2022-12-23 22:38 UTC, dimasster approved these changes

2022-12-24 07:29 UTC, AleXLaeR approved these changes

2022-12-24 20:38 UTC, merged