Unit tests for team link and positions endpoints
ita-social-projects/StreetCode pull request #264
Opened 2023-06-14 19:05 UTC by AndriiS1

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-06-14 20:03 UTC, KateYatsiuk requested changes

2023-06-14 20:03 UTC, KateYatsiuk commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Team/TeamMemberLink/GetAllTeamMembersLinksTest.cs
> +                .ReturnsAsync(GetTeamMemberLinksList());
The same problem with duplications of setup here

2023-06-15 07:32 UTC, Tysyatsky reviewed
Left some comments, correct them pls.

2023-06-15 07:32 UTC, Tysyatsky commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Team/Position/GetAllPositionTest.cs
> +            }
code styles, add tabs

2023-06-15 16:40 UTC, AndriiS1 commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Team/Position/CreatePositionTest.cs
> +                .Returns(1);
Thanks, solved

2023-06-15 16:43 UTC, KateYatsiuk approved these changes

2023-06-15 21:20 UTC, DanyilTerentiev approved these changes
Great work! I like how precise you covered all the cases

2023-06-15 21:52 UTC, AndriiS1 commented
> Great work! I like how precise you covered all the cases 

Glad to hear that

2023-06-16 08:26 UTC, Tysyatsky approved these changes
looks great.

2023-06-16 09:45 UTC, merged