Fixed CreateRelatedTermHandlerTest, GetTransactLinByStreetcodeIdHandl…
ita-social-projects/StreetCode pull request #271
Opened 2023-06-15 16:09 UTC by 666HellPlay666

…erTest, and created GetAllMainTeamHandlerTest

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-06-15 21:38 UTC, DanyilTerentiev commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/RelatedTerm/Create/CreateRelatedTermHandlerTests.cs
> +            result.IsFailed.Should().BeTrue();
Why don't you use Assert there?

2023-06-15 21:39 UTC, DanyilTerentiev commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Team/GetAllMainTeamHandlerTest.cs
> +            _mockRepo.Setup(r => r.TeamRepository.GetAllAsync(null,
Make a function for setups, please

2023-06-16 08:24 UTC, Tysyatsky commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Team/GetAllMainTeamHandlerTest.cs
> +            }
check the code style here.

2023-06-20 14:09 UTC, DanyilTerentiev approved these changes
Approved

2023-06-20 18:34 UTC, MaksBrat approved these changes

2023-06-21 15:58 UTC, NadiaKishchuk requested changes

2023-06-21 15:58 UTC, NadiaKishchuk commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/RelatedTerm/Create/CreateRelatedTermHandlerTests.cs
> +
please, use a separate method for setup

2023-06-21 15:58 UTC, NadiaKishchuk commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/RelatedTerm/Create/CreateRelatedTermHandlerTests.cs
> +            _repositoryWrapperMock.Verify(r => r.SaveChangesAsync(), Times.Never);
please, don't use magic strings

2023-06-21 15:58 UTC, NadiaKishchuk commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/RelatedTerm/Create/CreateRelatedTermHandlerTests.cs
> +            Assert.Equal("Cannot save changes in the database after related word creation!", result.Errors.First().Message);
the same here

2023-07-07 12:45 UTC, NadiaKishchuk approved these changes

2023-07-07 12:49 UTC, Tysyatsky commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/RelatedTerm/Create/CreateRelatedTermHandlerTests.cs
> +            Assert.Empty(result.Errors);
why do you removed multiple?

2023-07-07 12:49 UTC, Tysyatsky commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/RelatedTerm/Create/CreateRelatedTermHandlerTests.cs
> +            VerifyCreateAndSaveChangesNever();
same here

2023-07-07 12:49 UTC, Tysyatsky commented on Streetcode/Streetcode.XUnitTest/MediatRTests/Team/GetAllMainTeamHandlerTest.cs
> +
spacing

2023-07-10 11:47 UTC, merged