#272 Tests for news
ita-social-projects/StreetCode pull request #273
Opened 2023-06-15 18:08 UTC by MariaPadalka

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-06-15 21:22 UTC, DanyilTerentiev requested changes
I would consider placing setups for mocks for example into private functions, which would reduce duplicated code

2023-06-16 08:23 UTC, Tysyatsky reviewed
Check the code style and +1 to private methods.

2023-06-16 08:23 UTC, Tysyatsky commented on Streetcode/Streetcode.XUnitTest/MediatRTests/News/DeleteNewsTest.cs
> +
spacing is odd.

2023-06-16 08:23 UTC, Tysyatsky commented on Streetcode/Streetcode.XUnitTest/MediatRTests/News/DeleteNewsTest.cs
> +
same here

2023-06-16 08:23 UTC, Tysyatsky commented on Streetcode/Streetcode.XUnitTest/MediatRTests/News/UpdateNewsTest.cs
> +
same here

2023-06-16 08:23 UTC, Tysyatsky commented on Streetcode/Streetcode.XUnitTest/MediatRTests/News/UpdateNewsTest.cs
> +                .Returns("base64Image");
also try to move setups to private methods, so you don't need to repeat your code.

2023-06-16 10:51 UTC, NadiaKishchuk commented on Streetcode/Streetcode.XUnitTest/MediatRTests/News/DeleteNewsTest.cs
> +            _mockRepository.Setup(x => x.SaveChanges()).Throws(new Exception(expectedError));
you can set this value also in your mocking method passing the result of the method as a parameters

2023-06-16 10:51 UTC, NadiaKishchuk commented on Streetcode/Streetcode.XUnitTest/MediatRTests/News/GetAllNewsTest.cs
> +
the same is here

2023-06-19 15:57 UTC, KateYatsiuk approved these changes

2023-06-20 11:15 UTC, Dobriyr approved these changes

2023-06-20 14:29 UTC, Tysyatsky approved these changes

2023-06-21 06:53 UTC, merged