Added tests for FindStreetcodesWithMatchTitle() FindSortedStreetcodes() FindFilteredStreetcodes() in GetAllStreetcodehandler
ita-social-projects/StreetCode pull request #287
Opened 2023-06-20 09:10 UTC by maximu211

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-06-20 13:57 UTC, NadiaKishchuk commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/GetAllStreetcodesHandlerTests.cs
> +            repositoryWrapperMock.Setup(x => x.StreetcodeRepository).Returns(streetcodeRepositoryMock.Object);
You can create separate method for mocking and setuping objects

2023-06-20 14:05 UTC, DanyilTerentiev requested changes
Make separate methods and I approve it

2023-06-20 14:26 UTC, Tysyatsky reviewed
fix all comments and you are good to go

2023-06-20 14:26 UTC, Tysyatsky commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/GetAllStreetcodesHandlerTests.cs
> +
spacing

2023-06-22 06:31 UTC, maximu211 commented
i fixed it all) check it out

2023-06-27 12:15 UTC, OlehHatsko approved these changes
fix comments

2023-06-27 12:15 UTC, OlehHatsko commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/GetAllStreetcodesHandlerTests.cs
> +        [Fact]
Use common formatting conventions (Add empty line between methods)

2023-06-27 12:15 UTC, OlehHatsko commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/GetAllStreetcodesHandlerTests.cs
> +            var response = result.Value;
You do not need this variable. You can use result.Value.Streetcodes like parameter

2023-06-27 12:15 UTC, OlehHatsko commented on Streetcode/Streetcode.XUnitTest/MediatRTests/StreetCode/Streetcode/GetAllStreetcodesHandlerTests.cs
> +            IQueryable<StreetcodeContent> streetcodes = new List<StreetcodeContent>().AsQueryable();
why do you need explicit typing in here? consider common approach for creating variables

2023-07-07 16:04 UTC, MaksBrat approved these changes

2023-07-10 11:34 UTC, merged