Fix bugs #432 for fans valerii
ita-social-projects/StreetCode pull request #560
Opened 2023-08-04 12:42 UTC by ValDekh

dev
## JIRA

* [Main JIRA ticket](https://jira.softserve.academy/secure/RapidBoard.jspa?rapidView=id)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue
[Admin/Sources block] An admin can add more than 4000 symbols to the text field #432 

Chage text limit from 1000 to 10000 in Text Content field for fan

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  СI passed
- [ ]  Сode coverage >=95%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  All reviewers agreed to merge the PR
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2023-08-05 17:34 UTC, Tysyatsky requested changes

2023-08-05 17:34 UTC, Tysyatsky commented on Streetcode/StreetCode.Client
why is it here?

2023-08-05 17:34 UTC, Tysyatsky commented on Streetcode/Streetcode.WebApi/appsettings.Local.json
change it back to normal

2023-08-05 17:34 UTC, Tysyatsky commented on Streetcode/Streetcode.WebApi/appsettings.json
and here

2023-08-05 17:34 UTC, Tysyatsky commented on Streetcode/Streetcode.DAL/Persistence/ScriptsMigration/DDL_last_mig.sql
did you add new changes from migration to the script and do you still need migration files that was generated?

2023-08-07 11:02 UTC, ValDekh commented on Streetcode/Streetcode.WebApi/appsettings.Local.json
done

2023-08-07 11:05 UTC, ValDekh commented on Streetcode/Streetcode.WebApi/appsettings.json
done

2023-08-07 11:06 UTC, ValDekh commented on Streetcode/Streetcode.DAL/Persistence/ScriptsMigration/DDL_last_mig.sql
Yes, I thing we need both

2023-08-07 11:24 UTC, ValDekh commented on Streetcode/StreetCode.Client
done

2023-08-07 22:42 UTC, merged